// <auto-generated />
namespace CutTheCord.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class july7Master : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(july7Master));
        
        string IMigrationMetadata.Id
        {
            get { return "201707071541069_july7Master"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
